apiVersion: apps/v1
kind: Deployment
metadata:
  name: imsdepolyment
  

spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: ims
        image: bharathsunny3006/ims
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
              name: imsdev
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007 
             
            

         
