replicas: 3
labels: 
  app: web
image:
  registary: bharathsunny3006/ims
  tag: latest
service:
  port: 5000
  type: LoadBalancer
env:
  name: imsdev
  link: "mongodb://ims-deploy-mongoservice:27017/dbname"

labels1:
  app1: mongo
image1: 
  registry1: mongo
  tag1: latest
service1:
  port1: 27017
